data:
  raw_path: "C:/Users/user/Desktop/Projects/Mentors/PredictingUserChurn/data/raw/raw_data.csv"
  processed_path: "C:/Users/user/Desktop/Projects/Mentors/PredictingUserChurn/data/processed/processed_dataset.csv"
  processed_path_processed_path_without_unimportant: "C:/Users/user/Desktop/Projects/Mentors/PredictingUserChurn/data/processed/processed_dataset_1.csv"
  target: "Churn"
seed: '42'

