data:
  raw_path: "../data/raw/raw_data.csv"
  processed_path: "../data/processed/processed_dataset.csv"
  target: "Churn"
model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 100
    max_depth: 5
    random_state: 42